// <auto-generated />
using System;
using CompanyApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427131144_addSalaryProperty")]
    partial class addSalaryProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyApp.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MGR_SSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("MGR_StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID")
                        .HasName("PK_Department_ID");

                    b.HasIndex("MGR_SSN");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("CompanyApp.Models.DepartmentLocations", b =>
                {
                    b.Property<int>("DepartmentNum")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentNum", "Location")
                        .HasName("PK_DepartmentLocations");

                    b.ToTable("DepartmentLocations", (string)null);
                });

            modelBuilder.Entity("CompanyApp.Models.Dependent", b =>
                {
                    b.Property<string>("EmployeeSSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("BDate")
                        .HasColumnType("date");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeSSN", "Name")
                        .HasName("PK_Dependent");

                    b.ToTable("Dependent", (string)null);
                });

            modelBuilder.Entity("CompanyApp.Models.Employee", b =>
                {
                    b.Property<string>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BDate")
                        .HasColumnType("date");

                    b.Property<int?>("DeptNum")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MGR_SSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN")
                        .HasName("PK_Employee_SSN");

                    b.HasIndex("DeptNum");

                    b.HasIndex("MGR_SSN");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("CompanyApp.Models.Project", b =>
                {
                    b.Property<int>("ProjectNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectNumber"));

                    b.Property<int>("DepartmentNum")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNumber")
                        .HasName("PK_Project");

                    b.HasIndex("DepartmentNum");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("CompanyApp.Models.WorksOn", b =>
                {
                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeSSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NumberOfHours")
                        .HasColumnType("int");

                    b.HasKey("ProjectNumber", "EmployeeSSN")
                        .HasName("PK_WorksOn");

                    b.HasIndex("EmployeeSSN");

                    b.ToTable("WorksOn", (string)null);
                });

            modelBuilder.Entity("CompanyApp.Models.Department", b =>
                {
                    b.HasOne("CompanyApp.Models.Employee", "DepartmentManager")
                        .WithMany()
                        .HasForeignKey("MGR_SSN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepartmentManager");
                });

            modelBuilder.Entity("CompanyApp.Models.DepartmentLocations", b =>
                {
                    b.HasOne("CompanyApp.Models.Department", "Department")
                        .WithMany("Locations")
                        .HasForeignKey("DepartmentNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CompanyApp.Models.Dependent", b =>
                {
                    b.HasOne("CompanyApp.Models.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CompanyApp.Models.Employee", b =>
                {
                    b.HasOne("CompanyApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNum")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CompanyApp.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("MGR_SSN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CompanyApp.Models.Project", b =>
                {
                    b.HasOne("CompanyApp.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CompanyApp.Models.WorksOn", b =>
                {
                    b.HasOne("CompanyApp.Models.Employee", "Employee")
                        .WithMany("EmployeeProject")
                        .HasForeignKey("EmployeeSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyApp.Models.Project", "Project")
                        .WithMany("EmployeeProject")
                        .HasForeignKey("ProjectNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CompanyApp.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Locations");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CompanyApp.Models.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("EmployeeProject");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("CompanyApp.Models.Project", b =>
                {
                    b.Navigation("EmployeeProject");
                });
#pragma warning restore 612, 618
        }
    }
}
